services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bratotkat
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  bratatcat:
    build:
      context: .
      dockerfile: BratOtkat.WebApi/Dockerfile
    image: bratatcat
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=bratotkat;Username=postgres;Password=postgres
    depends_on:
      - db

volumes:
  db_data:
